<a href="https://colab.research.google.com/github/Stamatics-NumberstoNeurons/assignment1-basicpythonandnumpy-abhisheksharma414/blob/main/numpy_worksheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Exercises — 50 Problems

**Instructions:**
- Run the first cell to import NumPy before starting.
- Each exercise has a **Question** and an **Input** (where given).
- Write your solution in the `# Write your code here:` cell below each question.
- Run your cell to check your output.
- Do **not** modify the Input cells or the import cell.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [ ]:
# Run this cell before starting — do not modify
import numpy as np

## Section 1 — Array Basics (Exercises 1–10)

### Exercise 1 — NumPy Version

**Question:** Print the version of NumPy.


In [ ]:
# Write your code here:
print(np.__version__)

2.0.2


### Exercise 2 — 1D Array

**Question:** Create a 1D array of numbers from 0 to 9.


In [ ]:
# Write your code here:
print(np.arange(10))


[0 1 2 3 4 5 6 7 8 9]


### Exercise 3 — Boolean Array

**Question:** Create a 3×3 NumPy array of all `True`s.


In [ ]:
# Write your code here:
print(np.full((3, 3), True, dtype=bool))


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Exercise 4 — Filter Odd Numbers

**Question:** Extract all odd numbers from `arr`.


In [ ]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Write your code here:
print(np.extract(arr % 2 == 1, arr))
# np.add(arr, 1)
# print(arr)


[1 3 5 7 9]


### Exercise 5 — Replace In-Place

**Question:** Replace all odd numbers in `arr` with `-1`.


In [ ]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Write your code here:
arr[arr % 2 == 1] = -1
print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 6 — Replace Without Modifying Original

**Question:** Replace all odd numbers in `arr` with `-1` **without** changing the original array.


In [ ]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Write your code here:
arr2=arr.copy()
arr2[arr2 % 2 == 1] = -1
print(arr2)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 7 — Reshape Array

**Question:** Convert a 1D array to a 2D array with 2 rows.


In [ ]:
# Input — do not modify
arr = np.arange(10)

In [ ]:
# Write your code here:
arr2=arr.reshape(2,5)
print(arr2)


[[0 1 2 3 4]
 [5 6 7 8 9]]


### Exercise 8 — Vertical Stack

**Question:** Stack arrays `a` and `b` vertically.


In [ ]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
# Write your code here:
print(np.vstack((a,b)))


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Exercise 9 — Horizontal Stack

**Question:** Stack arrays `a` and `b` horizontally.


In [ ]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [ ]:
# Write your code here:
print(np.hstack((a,b)))


[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### Exercise 10 — Custom Sequence

**Question:** Create the following pattern **without hardcoding**. Use only NumPy functions and the input array `a`.

Expected output: `array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`


In [ ]:
# Input — do not modify
a = np.array([1, 2, 3])

In [ ]:
(np.repeat(a,3)),(np.tile(a,3))

(array([1, 1, 1, 2, 2, 2, 3, 3, 3]), array([1, 2, 3, 1, 2, 3, 1, 2, 3]))

In [ ]:
# Write your code here:
print(np.r_[np.repeat(a,3),np.tile(a,3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## Section 2 — Set Operations & Filtering (Exercises 11–19)

### Exercise 11 — Common Items

**Question:** Get the common items between arrays `a` and `b`.


In [ ]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
# Write your code here:
print(np.intersect1d(a,b))

[2 4]


### Exercise 12 — Remove Items

**Question:** From array `a`, remove all items present in array `b`.


In [ ]:
# Input — do not modify
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [ ]:
# Write your code here:
print(np.setdiff1d(a,b))

[1 2 3 4]


### Exercise 13 — Matching Positions

**Question:** Get the positions where elements of `a` and `b` match.


In [ ]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
# Write your code here:
print(np.where(a==b) )

(array([1, 3, 5, 7]),)


### Exercise 14 — Extract Range

**Question:** Get all items between 5 and 10 from array `a`.


In [ ]:
# Input — do not modify
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [ ]:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a[(a >= 5) & (a <= 10)])

[ 6  9 10]


### Exercise 15 — Vectorize a Function

**Question:** Convert the scalar function `maxx` below to work on two arrays.


In [ ]:
# Input — do not modify
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [ ]:
import numpy as np
maxx = np.vectorize(maxx)
print(maxx(a, b))

[6 7 9 8 9 7 5]


### Exercise 16 — Swap Columns

**Question:** Swap columns 1 and 2 in array `arr`.


In [ ]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [ ]:
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr[:, [0, 2, 1]])

[[0 2 1]
 [3 5 4]
 [6 8 7]]


### Exercise 17 — Swap Rows

**Question:** Swap rows 1 and 2 in array `arr`.


In [ ]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [ ]:
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr[[0, 2, 1], :])

[[0 1 2]
 [6 7 8]
 [3 4 5]]


### Exercise 18 — Reverse Rows

**Question:** Reverse the rows of the 2D array `arr`.


In [ ]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [ ]:
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr[::-1])

[[6 7 8]
 [3 4 5]
 [0 1 2]]


### Exercise 19 — Reverse Columns

**Question:** Reverse the columns of the 2D array `arr`.


In [ ]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [ ]:
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr[:, ::-1])

[[2 1 0]
 [5 4 3]
 [8 7 6]]


## Section 3 — Printing & Formatting (Exercises 20–24)

### Exercise 20 — Random Float Array

**Question:** Create a 2D array of shape 5×3 containing random decimal numbers between 5 and 10.


In [ ]:
print(np.random.uniform(low=5, high=10, size=(5, 3)))

[[6.32372062 9.63094983 5.45210127]
 [5.51040456 5.95275233 6.26281099]
 [6.7142313  6.85872001 9.50604422]
 [8.6788352  9.59351605 7.22242933]
 [9.97905838 8.69683832 9.05523209]]


### Exercise 21 — Decimal Places

**Question:** Print only 3 decimal places of the array `rand_arr`.


In [ ]:
# Input — do not modify
rand_arr = np.random.random((5,3))

In [ ]:
import numpy as np
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
print(rand_arr)

[[0.758 0.169 0.213]
 [0.262 0.151 0.704]
 [0.581 0.734 0.019]
 [0.503 0.556 0.008]
 [0.263 0.171 0.708]]


### Exercise 22 — Suppress Scientific Notation

**Question:** Pretty print `rand_arr` by suppressing scientific notation (like `1e10`).


In [ ]:
# Input — do not modify
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

In [ ]:
import numpy as np
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True, precision=6)
print(rand_arr)

[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


### Exercise 23 — Limit Print Output

**Question:** Limit the number of items printed in array `a` to a maximum of 6 elements.


In [ ]:
# Input — do not modify
a = np.arange(15)

In [ ]:
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]


### Exercise 24 — Print Full Array

**Question:** Print the full NumPy array `a` without truncating.


In [ ]:
# Input — do not modify
np.set_printoptions(threshold=6)
a = np.arange(15)

In [ ]:
import numpy as np
a = np.arange(15)
np.set_printoptions(threshold=np.inf)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Section 4 — Iris Dataset (Exercises 25–46)

### Exercise 25 — Import Dataset

**Question:** Import the Iris dataset keeping the text intact.

> URL: `https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv`


In [ ]:
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
iris_data = np.genfromtxt(url, delimiter=',', dtype='object')
print(iris_data[:3])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]


### Exercise 26 — Extract Text Column

**Question:** Extract the text column `species` from the 1D iris dataset imported in Exercise 25.

*# Make sure you have run Exercise 25 first so that iris_data is defined.*


In [ ]:
species = iris_data[:, 4]
print(species[:5])

[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


### Exercise 27 — 1D to 2D Array

**Question:** Convert the 1D iris dataset to a 2D array `iris_2d` by omitting the species text field.

*# Make sure you have run Exercise 25 first.*


In [ ]:
iris_2d = iris_data[:, :4].astype(float)
print(iris_2d[:3])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]


### Exercise 28 — Mean, Median, Std

**Question:** Find the mean, median, and standard deviation of the sepal length (1st column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [ ]:
sepal_length = iris_2d[:, 0]
print(f"Mean: {np.mean(sepal_length)}, Median: {np.median(sepal_length)}, Std: {np.std(sepal_length)}")

Mean: 5.843333333333334, Median: 5.8, Std: 0.8253012917851409


### Exercise 29 — Normalize Array

**Question:** Create a normalized form of iris's sepal length whose values range exactly between 0 and 1 (minimum → 0, maximum → 1).

*# Make sure you have run Exercise 27 first.*


In [ ]:
sepal_length = iris_2d[:, 0]
normalized_sepal_length = (sepal_length - np.min(sepal_length)) / (np.max(sepal_length) - np.min(sepal_length))
print(normalized_sepal_length[:5])

[0.222222 0.166667 0.111111 0.083333 0.194444]


### Exercise 30 — Softmax Score

**Question:** Compute the softmax score of the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [ ]:
sepal_length = iris_2d[:, 0]
e_x = np.exp(sepal_length - np.max(sepal_length))
softmax_scores = e_x / e_x.sum()
print(softmax_scores[:5])

[0.00222  0.001817 0.001488 0.001346 0.002008]


### Exercise 31 — Percentile Scores

**Question:** Find the 5th and 95th percentile of iris's sepal length.

*# Make sure you have run Exercise 27 first.*


In [ ]:
sepal_length = iris_2d[:, 0]
print(f"5th Percentile: {np.percentile(sepal_length, 5)}, 95th Percentile: {np.percentile(sepal_length, 95)}")

5th Percentile: 4.6, 95th Percentile: 7.254999999999998


### Exercise 32 — Insert Missing Values

**Question:** Insert `np.nan` values at 20 random positions in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [ ]:
iris_2d_nan = iris_2d.copy()
np.random.seed(100)
n_missing = 20
r = np.random.randint(0, iris_2d_nan.shape[0], n_missing)
c = np.random.randint(0, iris_2d_nan.shape[1], n_missing)
iris_2d_nan[r, c] = np.nan
print(iris_2d_nan[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### Exercise 33 — Find Missing Values

**Question:** Find the **number** and **position** of missing values in `iris_2d`'s sepal length (1st column).

*# Make sure you have run Exercise 32 first.*


In [ ]:
sepal_length_nan = iris_2d_nan[:, 0]
n_nan = np.isnan(sepal_length_nan).sum()
nan_positions = np.where(np.isnan(sepal_length_nan))
print(f"Number of missing values: {n_nan}, Positions of missing values: {nan_positions}")

Number of missing values: 4, Positions of missing values: (array([14, 34, 79, 87]),)


### Exercise 34 — Multi-Condition Filter

**Question:** Filter the rows of `iris_2d` that have:
- petal length (3rd column) > 1.5, **and**
- sepal length (1st column) < 5.0

*# Make sure you have run Exercise 32 first.*


In [ ]:
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print(filtered_rows[:5])

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]]


### Exercise 35 — Drop Rows with NaN

**Question:** Select rows of `iris_2d` that do **not** have any `nan` value.

*# Make sure you have run Exercise 32 first.*


In [ ]:
rows_without_nan = iris_2d_nan[~np.isnan(iris_2d_nan).any(axis=1)]
print(rows_without_nan[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### Exercise 36 — Correlation

**Question:** Find the correlation between sepal length (1st column) and petal length (3rd column) in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [ ]:
correlation = np.corrcoef(iris_2d[:, 0], iris_2d[:, 2])
print(correlation)

[[1.       0.871754]
 [0.871754 1.      ]]


### Exercise 37 — Check for NaN

**Question:** Find out if `iris_2d` has any missing values.

*# Make sure you have run Exercise 32 first.*


In [ ]:
has_nan = np.isnan(iris_2d_nan).any()
print(has_nan)

True


### Exercise 38 — Replace NaN with 0

**Question:** Replace all occurrences of `nan` with `0` in `iris_2d`.

*# Make sure you have run Exercise 32 first.*


In [ ]:
iris_2d_no_nan = np.nan_to_num(iris_2d_nan, nan=0)
print(iris_2d_no_nan[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### Exercise 39 — Unique Value Counts

**Question:** Find the unique values and their counts in iris's species column.

*# Make sure you have run Exercise 25 first.*


In [ ]:
unique_species, counts = np.unique(species, return_counts=True)
print(dict(zip(unique_species, counts)))

{b'Iris-setosa': np.int64(50), b'Iris-versicolor': np.int64(50), b'Iris-virginica': np.int64(50)}


### Exercise 40 — Numeric to Categorical

**Question:** Bin the petal length (3rd column) of `iris_2d` to form a text array using these rules:
- `< 3` → `'small'`
- `3–5` → `'medium'`
- `>= 5` → `'large'`

*# Make sure you have run Exercise 27 first.*


In [ ]:
petal_length = iris_2d[:, 2]
bins = np.array([0, 3, 5, np.inf])
labels = np.array(['small', 'medium', 'large'])
binned_petal_length = labels[np.digitize(petal_length, bins) - 1]
print(binned_petal_length[:5])

['small' 'small' 'small' 'small' 'small']


### Exercise 41 — Create New Column

**Question:** Create a new column for **volume** in `iris_2d`, where:

> volume = (π × petal_length × sepal_length²) / 3

*# Make sure you have run Exercise 27 first.*


In [ ]:
sepal_length = iris_2d[:, 0]
petal_length = iris_2d[:, 2]
volume = (np.pi * petal_length * sepal_length**2) / 3
iris_2d_with_volume = np.column_stack([iris_2d, volume])
print(iris_2d_with_volume[:5])

[[ 5.1       3.5       1.4       0.2      38.132652]
 [ 4.9       3.        1.4       0.2      35.200498]
 [ 4.7       3.2       1.3       0.2      30.072372]
 [ 4.6       3.1       1.5       0.2      33.23805 ]
 [ 5.        3.6       1.4       0.2      36.651914]]


### Exercise 42 — Probabilistic Sampling

**Question:** Randomly sample iris's species such that **setosa** appears **twice** as often as versicolor and virginica.

*# Make sure you have run Exercise 25 first.*


In [ ]:
np.random.seed(100)
unique_species, counts = np.unique(species, return_counts=True)
prob = [0.5, 0.25, 0.25]
sampled_indices = np.random.choice(len(unique_species), size=10, p=prob)
sampled_species = unique_species[sampled_indices]
print(sampled_species)

[b'Iris-versicolor' b'Iris-setosa' b'Iris-setosa' b'Iris-virginica'
 b'Iris-setosa' b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica'
 b'Iris-setosa' b'Iris-versicolor']


### Exercise 43 — Second Largest Value

**Question:** Find the **second longest** petal length among iris samples of species **setosa**.

*# Make sure you have run Exercise 25 first.*


In [ ]:
setosa_petal_lengths = iris_2d[species == b'Iris-setosa', 2]
second_longest = np.sort(setosa_petal_lengths)[-2]
print(second_longest)

1.9


### Exercise 44 — Sort 2D Array by Column

**Question:** Sort the iris dataset based on the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [ ]:
sorted_iris_2d = iris_2d[iris_2d[:, 0].argsort()]
print(sorted_iris_2d[:5])

[[4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]]


### Exercise 45 — Most Frequent Value

**Question:** Find the most frequent value of petal length (3rd column) in the iris dataset.

*# Make sure you have run Exercise 27 first.*


In [ ]:
petal_length = iris_2d[:, 2]
values, counts = np.unique(petal_length, return_counts=True)
most_frequent_value = values[np.argmax(counts)]
print(most_frequent_value)

1.5


### Exercise 46 — First Value Greater Than

**Question:** Find the position of the **first occurrence** of a value greater than 1.0 in the petal width (4th column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [ ]:
petal_width = iris_2d[:, 3]
position = np.where(petal_width > 1.0)[0][0]
print(position)

50


## Section 5 — Miscellaneous (Exercises 47–50)

### Exercise 47 — Clip Values

**Question:** From array `a`, replace all values **greater than 30** with `30`, and all values **less than 10** with `10`.


In [ ]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [ ]:
import numpy as np
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
clipped_a = np.clip(a, 10, 30)
print(clipped_a)

[27.626842 14.6401   21.801362 30.       10.       10.       30.
 30.       10.       29.179573 30.       11.250904 10.081083 10.
 11.765177 30.       30.       10.       30.       14.429614]


### Exercise 48 — Top N Positions

**Question:** Get the positions of the **top 5 maximum values** in array `a`.


In [ ]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [ ]:
top_5_indices = np.argsort(a)[-5:]
print(top_5_indices)

[18  7  3 10 15]


### Exercise 49 — Row-wise Unique Counts

**Question:** Compute the counts of unique values **row-wise** in the input array.


In [ ]:
# Input — do not modify
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))

In [ ]:
import numpy as np
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))
output = [np.unique(row, return_counts=True) for row in arr]
for values, counts in output:
    print(dict(zip(values, counts)))

{np.int64(1): np.int64(1), np.int64(3): np.int64(2), np.int64(4): np.int64(1), np.int64(5): np.int64(1), np.int64(6): np.int64(1), np.int64(8): np.int64(2), np.int64(9): np.int64(2)}
{np.int64(1): np.int64(2), np.int64(2): np.int64(1), np.int64(3): np.int64(3), np.int64(5): np.int64(1), np.int64(7): np.int64(1), np.int64(9): np.int64(1), np.int64(10): np.int64(1)}
{np.int64(2): np.int64(3), np.int64(4): np.int64(2), np.int64(5): np.int64(3), np.int64(6): np.int64(1), np.int64(8): np.int64(1)}
{np.int64(1): np.int64(1), np.int64(3): np.int64(2), np.int64(4): np.int64(1), np.int64(6): np.int64(1), np.int64(8): np.int64(2), np.int64(9): np.int64(1), np.int64(10): np.int64(2)}
{np.int64(1): np.int64(2), np.int64(2): np.int64(2), np.int64(3): np.int64(2), np.int64(6): np.int64(1), np.int64(7): np.int64(1), np.int64(8): np.int64(1), np.int64(9): np.int64(1)}
{np.int64(1): np.int64(1), np.int64(2): np.int64(1), np.int64(3): np.int64(1), np.int64(4): np.int64(1), np.int64(5): np.int64(1), np.i

### Exercise 50 — Flatten Array of Arrays

**Question:** Convert `arr_2d` (an array of arrays) into a flat 1D array.


In [ ]:
# Input — do not modify
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)
arr_2d = np.array([arr1, arr2, arr3], dtype=object)

In [ ]:
import numpy as np
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)
arr_2d = np.array([arr1, arr2, arr3], dtype=object)
flattened_arr = np.concatenate(arr_2d)
print(flattened_arr)

[0 1 2 3 4 5 6 7 8 9]


---

## 🎉 Well done!

You've completed all 50 exercises. Review any exercises you found tricky and revisit the NumPy documentation for deeper understanding.